# This file was generated by the {rix} R package v0.17.2 on 2025-11-26
# with following call:
# >rix(r_ver = "00f459c69df1086032022158cfe9f8f8530b1788",
#  > r_pkgs = c("ggplot2",
#  > "patchwork",
#  > "ggpubr",
#  > "rjson",
#  > "Matrix",
#  > "hdf5r",
#  > "Seurat",
#  > "RColorBrewer",
#  > "knitr",
#  > "RUnit",
#  > "rmarkdown",
#  > "testthat",
#  > "roxygen2",
#  > "devtools",
#  > "rix",
#  > "rlang",
#  > "styler",
#  > "lintr"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(package_name = "Vesalius",
#  > repo_url = "https://github.com/WonLab-CS/Vesalius",
#  > commit = "bb4aa3d"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses upstream nixpkgs' revision 00f459c69df1086032022158cfe9f8f8530b1788 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/00f459c69df1086032022158cfe9f8f8530b1788.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      devtools
      ggplot2
      ggpubr
      hdf5r
      knitr
      lintr
      Matrix
      patchwork
      RColorBrewer
      rix
      rjson
      rlang
      rmarkdown
      roxygen2
      RUnit
      Seurat
      styler
      testthat;
  };
 
    Vesalius = (pkgs.rPackages.buildRPackage {
      name = "Vesalius";
      src = pkgs.fetchgit {
        url = "https://github.com/WonLab-CS/Vesalius";
        rev = "bb4aa3d";
        sha256 = "sha256-Cx9CYwkIjdAlVQhUXR479sY1TsetZ0ExEj1z9TU95t8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          deldir
          sp
          tvR
          Matrix
          RColorBrewer
          future
          future_apply
          imagerExtra
          Signac
          ggpubr
          lmtest
          infix
          Seurat
          SeuratObject
          imager
          DESeq2
          RANN
          dplyr
          edgeR
          ggplot2
          igraph
          pwr
          purrr
          patchwork
          ggnewscale
          kohonen
          Rcpp
          RcppEigen
          TreeDist;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ Vesalius rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
